; ESP32-S3-N16R8 Multi-Tool
; https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html

[env:esp32-s3-n16r8]
platform  = espressif32 @ 6.4.0
board     = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size    = 16MB
board_build.partitions    = partitions.csv
board_upload.flash_size   = 16MB

monitor_speed = 115200
upload_speed  = 921600
monitor_filters = esp32_exception_decoder

lib_compat_mode = strict
lib_ldf_mode    = deep+  

build_flags =
    -D TOUCH_CS=-1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_TINYUSB_HID_ENABLED=1
    -D CONFIG_TINYUSB_CDC_ENABLED=1
    -Wl,--allow-multiple-definition
    -D CONFIG_BT_NIMBLE_PINNED_TO_CORE=0

    ; ---- NimBLE tuning ----
    -D CONFIG_BT_NIMBLE_TASK_STACK_SIZE=4096
    -D CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=4096
    -D CONFIG_BT_NIMBLE_EXT_ADV=0
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D CONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=0

    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=14
    -D TFT_BL=15
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=0
    -D LOAD_FONT4=0
    -D LOAD_FONT6=0
    -D LOAD_FONT7=0
    -D LOAD_FONT8=0
    -D SMOOTH_FONT=0
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D SUPPORT_TRANSACTIONS=1

    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DNFC_INTERFACE_I2C

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/Adafruit MCP23017 Arduino Library
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    lsatan/SmartRC-CC1101-Driver-Lib @ ^3.0.2
    sui77/rc-switch @ ^2.6.4
    bblanchon/ArduinoJson @ ^6.21.1
    h2zero/NimBLE-Arduino @ 2.5.1
    mikalhart/TinyGPSPlus @ ^1.0.3
    sandeepmistry/LoRa @ ^0.8.0
    ciniml/WireGuard-ESP32 @ ^0.1.5
    https://github.com/adafruit/Adafruit_TinyUSB_Arduino
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ESP32Async/AsyncTCP @ 3.3.2
    https://github.com/0ldev/Politician
    nrf24/RF24 @ ^1.6.0
    handmade0octopus/ESP32-TWAI-CAN @ ^1.0.1
    autowp/autowp-mcp2515 @ ^1.0.3
    https://github.com/Seeed-Studio/PN532.git